[package]
name = "anglish"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
dotenv = "0.15.0"
ferrous-llm = {version = "0.6.1", features = ["ollama", "specta"]}
specta = "1.0.5"
testcontainers = "0.25.0"
tokio = { version = "1.47.1", features = ["full"] }
